server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config-server
#  profiles:
#    active: native
  cloud:
    config:
      label: master
      server:
#        native:
#          search-locations: classpath:/config/
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
          username: your username
          password: your password